### ISSUE TITLE
trouble with xgboost version

### ISSUE THREAD

**Issue by boweny920** [amina01/AcRanker#2]
Hi, 

When trying to run the Acranker locally, the following error came up:

Traceback (most recent call last):
  File "acranker.py", line 14, in <module>
    analyzePhage(prot_path, rank_path)
  File "/mnt/array1/bowen/TOOLS/AcRanker/server2.py", line 237, in analyzePhage
    model=pickle.load(open('xgb_rank.pickle', 'rb'))
  File "/home/yangbowen/.local/lib/python3.6/site-packages/xgboost/core.py", line 1093, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "/home/yangbowen/.local/lib/python3.6/site-packages/xgboost/core.py", line 189, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))

I believe this is a problem with the version of xgboost being used. I have the '1.0.0' version. could you help me bypass this error?

**Comment by boweny920** [comment]
Hi, 

So we figured out that the xgboost have to be version 0.9. After fixing that another error came up:

Traceback (most recent call last):
  File "acranker.py", line 14, in <module>
    analyzePhage(prot_path, rank_path)
  File "/home/haidong/project/acranker_tmp/AcRanker/server2.py", line 240, in analyzePhage
    scores =  model.predict(X)
  File "/home/haidong/project/acranker_tmp/AcRanker/xgbranker.py", line 135, in predict
    test_dmatrix = DMatrix(X, missing=self.missing)
  File "/home/haidong/miniconda3/lib/python3.7/site-packages/xgboost/core.py", line 404, in __init__
    self._init_from_npy2d(data, missing, nthread)
  File "/home/haidong/miniconda3/lib/python3.7/site-packages/xgboost/core.py", line 474, in _init_from_npy2d
    raise ValueError('Input numpy.ndarray must be 2 dimensional')
ValueError: Input numpy.ndarray must be 2 dimensional

Not sure what is the cause of this tho.

**Comment by amina01** [comment]
Please send me a sample input file. That may help me find the source of the error.

**Comment by boweny920** [comment]
Sounds good. Here is the link to were you can download the data i used: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/010/525/GCF_000010525.1_ASM1052v1/GCF_000010525.1_ASM1052v1_protein.faa.gz

Thanks again!

**Comment by amina01** [comment]
Hi,
Updated the code. Using dictionaries Python-2.7-style was causing the issue. Should work fine now. Let me know if it doesn't.

**Comment by snayfach** [comment]
...I've run into this same bug using the latest version

**Comment by snayfach** [comment]
update: the issue was caused by stop codons (*) in the protein sequence (and the necessary xgboost version 0.90). the readme should be updated this this info to save others time in the future
