### ISSUE TITLE
Error when using AcRanker: ImportError: cannot import name 'joblib' from 'sklearn.externals'.

### ISSUE THREAD

**Issue by jdcfc** [amina01/AcRanker#6]
Hi there,

When I try to use the AcRanker tool through Conda, I receive the following error:

`Traceback (most recent call last):
  File "/home/ubuntu/AcRanker/acranker.py", line 9, in <module>
    from server2 import *
  File "/home/ubuntu/AcRanker/server2.py", line 29, in <module>
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib' from 'sklearn.externals' (/opt/miniconda3/envs/AcRanker/lib/python3.11/site-packages/sklearn/externals/__init__.py)
(AcRanker) ubuntu@jdtest2:~/AcRanker$ python acranker.py --help
Traceback (most recent call last):
  File "/home/ubuntu/AcRanker/acranker.py", line 9, in <module>
    from server2 import *
  File "/home/ubuntu/AcRanker/server2.py", line 29, in <module>
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib' from 'sklearn.externals' (/opt/miniconda3/envs/AcRanker/lib/python3.11/site-packages/sklearn/externals/__init__.py)`

I was wondering if anyone has come across this error and if so, how they resolved it?

Thanks in advance!

**Comment by TahaAhmad4411** [comment]
Hi, you need to install joblib separately because it is deprecated in newer models of sklearn.externals
Worked for me after 
"!pip install joblib" and then "!import joblib" in colab
